### ISSUE TITLE
Width of a formularelement in Studio increases when the CollapsiblePanel is expanded

### ISSUE THREAD

**Issue by timolemke** [tallence/core-forms#1]
When expanding the collapsiblePanel of a FormElement the width of the collapsiblePanel might increase. The browser reacts with inserting a horizontal scrollBar into the area with applied formElements. which is not wanted here.

This seems to happen, when there are some more applied formElements which increases the height of the area of applied formElements so that a vertical scrollBar is visible.

See this screenshot: 
![selection_002](https://user-images.githubusercontent.com/3449367/38796672-669f8830-415c-11e8-9139-c055d8f0a481.png)

**Comment by TallenceJanHendrikPopp** [comment]
I can't reproduce this bug anymore. I think the bug was fixed by the last big refactoring. @timolemke, can you test it again and then close or update this ticket ?

**Comment by timolemke** [comment]
@TallenceJanHendrikPopp it is still reproducible at the demo environment...

**Comment by timolemke** [comment]
yep, seems to be fixed. At least with CM10
